#!/usr/bin/env bash
if ! head -1 "$1" | grep -qE "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid. Please reference https://www.conventionalcommits.org/en/v1.0.0/ for commit standards." >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,50}$"; then
    echo "Aborting commit. Your commit message is too long. Please reference https://www.conventionalcommits.org/en/v1.0.0/ for commit standards." >&2
    exit 1
fi